### ISSUE TITLE
Prototype code

### ISSUE THREAD

**Issue by alonshmilo** [alonshmilo/MedicalData_jce#10]
# Issue: Prototype code

### Explanation:
Writing first code for a feature. Developing learning stage.

### Checklist:
- [x] Code
- [x] Reading
- [x] Documenting reading
- [x] Project book
- [x] Advisor consult

**Comment by alonshmilo** [comment]
Waiting for Advisor's input - initial images to analyze

**Comment by alonshmilo** [comment]
Inputs arrived.
Code writing - imageHandler: functions for loading images and other manipulations.

**Comment by alonshmilo** [comment]
@stavdv on preparing the inputs
@alonshmilo on networks

**Comment by alonshmilo** [comment]
Due to meeting with Academic Advisor - change in work:
Article reading for finding ways to numbering ribs from segmented pictures, preparing deep network from medic-work previous implemented.

**Comment by stavdv** [comment]
Working on deepmedic
Making configuration files do it will work in our images

**Comment by alonshmilo** [comment]
Done 🥇
