### ISSUE TITLE
Code tests - Prototype stage

### ISSUE THREAD

**Issue by alonshmilo** [alonshmilo/MedicalData_jce#12]
# Issue: Code tests

### Explanation:
* Code tests planning for the rest of the project.
* Testing code, borderline cases.
[Types of tests](http://is.gd/typesoftests)

### Checklist:
- [x] Code
- [x] Reading
- [x] Documenting reading
- [x] Project book
- [x] Advisor consult

- [x] Model
- [x] Training 
- [x] Test

**Comment by alonshmilo** [comment]
Tests will be held during work: 
1. Set up configuration files using our data. @stavdv 
2. Training.
3. Testing.

**Comment by stavdv** [comment]
Testing with the CNN model was done successfully.

**Comment by stavdv** [comment]
Tests needed on our images.
1. If loading images us done
2. Importing results

**Comment by stavdv** [comment]
Tests passed successfully.
Test program for the future was prepared - in the report and on wiki site
