### ISSUE TITLE
Prototype video

### ISSUE THREAD

**Issue by alonshmilo** [alonshmilo/MedicalData_jce#14]
# Issue: Prototype video

### Explanation:
A short video, 2-3 minutes, that explains the project's goal and what have been done until now.

### Checklist:
- [x] Scripts
- [x] Work summary
- [x] Recording
- [x] Correctness
- [x] Quality
- [x] Uploading

**Comment by alonshmilo** [comment]
1. Presentation is being prepared in Keynote

**Comment by alonshmilo** [comment]
2. Keynote's almost ready. Left: add pictures of running DeepMedic.

**Comment by stavdv** [comment]
3. Keynote's ready.
4. Video recorded 3 times - third time's a charm

**Comment by stavdv** [comment]
5. Video uploaded https://youtu.be/Zr0yy6b0b8M
