### ISSUE TITLE
Code Tests - Mid-term stage

### ISSUE THREAD

**Issue by alonshmilo** [alonshmilo/MedicalData_jce#17]
# Issue: Tests - Structure stage

### Explanation:
Testing code, borderline cases.

### Checklist:
- [x] Code
- [x] Reading
- [x] Documenting reading
- [x] Project book
- [x] Advisor consult

**Comment by alonshmilo** [comment]
Unit tests:
Synthetic data for Deepmedic and yolo @stavdv

**Comment by alonshmilo** [comment]
Synthetic data produced, according to #31

**Comment by alonshmilo** [comment]
Synthetic data created using Phantom method in MATLAB.

Model - created
Train - done well: ellipse was used as data - and as a result, all ellipses were segmented in original scan.

**Comment by alonshmilo** [comment]
Test - done well.
Now need to examine evaluations according to [EvaluateSegmentation](https://github.com/Visceral-Project/EvaluateSegmentation) @alonshmilo

**Comment by stavdv** [comment]
Code tests were made:
1. EvaluateSegmentation
2. Synthetic data
👍
