### ISSUE TITLE
Project book (Finish report)

### ISSUE THREAD

**Issue by alonshmilo** [alonshmilo/MedicalData_jce#23]
# Issue: Project book (Finish report)

### Explanation:
Writing project book, according to: [Engineering writing instructions](http://www.ariel.ac.il/images/stories/site/departments/ee/writeeng.pdf) and [book form](http://www.ariel.ac.il/images/stories/site/departments/ee/book1.pdf)

**Comment by alonshmilo** [comment]
Opened on dropbox station.
Need to combine: from project proposal to the general documents presented at project's site

**Comment by alonshmilo** [comment]
Report written,
Missing:

- [x] Content list
- [x] Images of DeepMedic
- [x] Last image of Yolo
- [x] Thanks
- [ ] Link to video
- [x] Dice results

Academic advisor's comments:
- [x] Structure expand - deepmedic
- [x] Structure expand - yolo
- [x] ML expand

**Comment by alonshmilo** [comment]
Report written, got more comments from advisor. To be finished today.

**Comment by stavdv** [comment]
Today or tomorrow...
