### ISSUE TITLE
DeepMedic code

### ISSUE THREAD

**Issue by stavdv** [alonshmilo/MedicalData_jce#31]
# Issue: DeepMedic code

### Checklist:
- [x] Background review
- [x] Added to working document
- [ ] Tests passed
- [x] On iteration goals
- [x] Consult

**Comment by alonshmilo** [comment]
Working @stavdv

**Comment by alonshmilo** [comment]
Bug:

File "./deepMedicRun", line 99, in <module> deepMedicTrain.deepMedicTrainMain(absPathToTrainConf,
 absPathToCnnModelGivenInCmdLine, cnnInstanceLoaded, filenameAndPathWhereNewlyCreatedModelWasSaved) File "/Users/stavbarazani/Documents/deepmedic/deepmedic/frontEndModules/deepMedicTrain.py", line 441, in deepMedicTrainMain do_training(*trainSessionParameters.getTupleForCnnTraining())
 File "/Users/stavbarazani/Documents/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py", line 1134, in do_training reflectImageWithHalfProbDuringTraining = [0,0,0] File "/Users/stavbarazani/Documents/deepmedic/deepmedic/trainValidateTestVisualiseParallel.py",
 line 858, in getTheArraysOfImageChannelsAndLesionsToLoadToGpuForSubepoch np.asarray(lesionLabelsForTheCentralPredictedPartOfSegmentsInGpUForSubepoch, dtype="float32"), File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy-1.12.0-py2.7-macosx-10.6-intel.egg/numpy/core/numeric.py",
 line 531, in asarray return array(a, dtype, copy=False, order=order) ValueError: could not broadcast input array from shape (1,0) into shape (1,1)

**Comment by alonshmilo** [comment]
Debugs:
Problems with 'list' .shape

**Comment by stavdv** [comment]
Debugs:
regarding the .shape debug lines, just cast the list to a np array before doing the .shape then. something like:
print "DEBUGGING! imagePartsChannelsToLoadOnGpuForSubepoch.shape=", (np.asarray(imagePartsChannelsToLoadOnGpuForSubepoch)).shape

Image resize script CRresize2.
Resize successful.
Now setting new data for network.

**Comment by alonshmilo** [comment]
Problems with dimensions.
@stavdv : Channel, GTlabels, and ROI should be in the same dimensions
The v=best thing is to see what's the example is.

**Comment by stavdv** [comment]
The 3 provided images was different dimensions. Channel=[512,512,78], GT = [512,512,26], ROI = [512,512,58].
and now:  Channel=[240,240,155], GT = [240,240,155], ROI = [240,240,155].

after using the new data for network:
new problem: 
ValueError: probabilities are not non-negative

**Comment by alonshmilo** [comment]
New scans for data. Now shrinking to the right size

**Comment by stavdv** [comment]
Currently MATLAB work to fit data.

**Comment by alonshmilo** [comment]
Producing synthetic data, using [phantom](https://www.mathworks.com/help/images/ref/phantom.html#f6-195623)
Creating scan.nii.gz, gt.nii.gz and roi.nii.gz

**Comment by alonshmilo** [comment]
From tests #17:
Synthetic data is OK 👍 

Now the bug surrounds the original data - checking what is wrong there @stavdv

**Comment by stavdv** [comment]
DeepMedic works with our data 👍 @alonshmilo

**Comment by alonshmilo** [comment]
Towards the end on iteration 2 (Construct report): 

- [ ] Examine evaluations according to [EvaluateSegmentation](https://github.com/Visceral-Project/EvaluateSegmentation). @alonshmilo

- [x] Make changes in resize so gt and roi mask won't be floaty. @stavdv

**Comment by stavdv** [comment]
resize works. now changing images to create sets for training and testing

**Comment by alonshmilo** [comment]
EvaluateSegmentation does not work on mac.
Problems with running on Ubuntu, although it supports it.
Works on Virtual machine Windows 8.1 - If there will be no other choice - we'll work with that.

@stavdv to make 2 more sets and 3 new sessions to make the DICE check with tool. Finish expected on Tuesday.

**Comment by alonshmilo** [comment]
Working with ITK-SNAP to create new segmentation and ROI mask from scans. New set created from 512x512x187 scan.
Now waiting for DICE results - tommorow.

**Comment by stavdv** [comment]
Train, test and validation on 3 different set - done 👍 
@alonshmilo Make dice evaluation.

**Comment by alonshmilo** [comment]
Dice results: 0.54.

More evaluation with new gt and roi on next Iteration.
