### ISSUE TITLE
Cascaded-FCN code - CRF method

### ISSUE THREAD

**Issue by stavdv** [alonshmilo/MedicalData_jce#32]
# Issue: Cascaded-FCN code - CRF method

### Checklist:
- [x] Background review
- [x] Added to working document
- [x] Tests passed
- [x] On iteration goals
- [x] Consult

**Comment by alonshmilo** [comment]
working on

**Comment by alonshmilo** [comment]
caffe installation

**Comment by alonshmilo** [comment]
Caffe is horrible. An alternative was suggested my advisor: 
https://pjreddie.com/darknet/yolo/
@stavdv checking it out
Should save the classifier, and gives visual nice results

**Comment by stavdv** [comment]
Checking yolo instead

**Comment by alonshmilo** [comment]
Unnecessary 👍
