### ISSUE TITLE
Yolo classifier

### ISSUE THREAD

**Issue by alonshmilo** [alonshmilo/MedicalData_jce#35]
# Issue: Yolo classifier

### Explanation: 
Check the Yolo system for classifier. It is a 2d system but gives a great visualized classification.
https://pjreddie.com/darknet/yolo/

### Checklist:
- [x] Background review
- [x] Added to working document
- [x] Tests passed
- [x] On iteration goals
- [x] Consult

**Comment by alonshmilo** [comment]
First work with the tool succeeded. It's working on the examples given.

**Comment by stavdv** [comment]
Yolo works on our macs with simple examples. Now figuring out how to change the examples to bones.

**Comment by stavdv** [comment]
Checking gray2rgb functions

**Comment by alonshmilo** [comment]
convert.py works well, file in repo updated.

Left for end of iteration 2 (construct report):

- [ ] Make changes to code according to guide.

**Comment by alonshmilo** [comment]
Created: bone.data, bones.name, training is on queue - now creating weights file.

**Comment by stavdv** [comment]
Due to gray2rgb: no need, there is an export option in itk-snap: for slice and for series.

**Comment by alonshmilo** [comment]
Training with real data takes a lot of time.
We've stopped the process, and:
1. Trying with coco as explained on website.
2. Trying with 1 or 2 gt label images.
3. Trying with 1 or 2 scan images.
It might take several days to week or 2. We are working with only CPU.

This is NOT up to the end of iteration - it will move to iteration no.3

**Comment by alonshmilo** [comment]
For next iteration:
1. Train on coco data
2. Train on simple bone data
3. Train on full data.
