### ISSUE TITLE
DeepMedic - accuracy

### ISSUE THREAD

**Issue by alonshmilo** [alonshmilo/MedicalData_jce#36]
# Issue: DeepMedic - accuracy

### Checklist:
- [x] Background review
- [x] Added to working document
- [x] Tests passed
- [x] On iteration goals
- [x] Consult

**Comment by stavdv** [comment]
Both me and @alonshmilo working on new segmentations images to raise accuracy in train, validation an test

**Comment by alonshmilo** [comment]
@stavdv is making new segmentations and trying to run deep medic on GPU computer

**Comment by stavdv** [comment]
GPU computer works, now running full network of deepmedic

**Comment by stavdv** [comment]
Training for full network was over this morning. Next - Test for full network and them the whole process for our data. Waiting for computer to be available from Yolo running @alonshmilo 😄

**Comment by stavdv** [comment]
Running test on GPU computer - original data.
Finished in several minutes - according to terminal log: DICE of ~0.87

**Now running model and train on our data** - finally 😄

**Comment by stavdv** [comment]
As a test, running train and test on bone damaged data and received fine results in relative to the data.

**Comment by stavdv** [comment]
Another run is on GPU computer

**Comment by stavdv** [comment]
👍
